version: '3'
services:

  c2-server:
    build:
      context: c2-server
    networks:
      c2_network:
        ipv4_address: 172.98.0.2
    ports:
      - "8001:8001"
    environment:
      - SERVER_HOST=172.98.0.2
      - SERVER_PORT=8001
      - SECREY_KEY=HICjfJURXL74+/fB8AM/gIKsJLowIxMOiYJ/ruYT+qE=
      - PROTOCOL=https
      - REQUEST_TIMEOUT=3
      - CLIENT_LIVELINESS_THRESHOLD_MINUTES=1
      - COMMAND_AGE_THRESHOLD_MINUTES=60
      - STATUS_REFRESH_INTERVAL_SECONDS=10
  
  c2-client-1:
    build:
      context: c2-client
    networks:
      - c2_network
    ports:
      - "8070:8070"
    environment:
      - CLIENT_PORT=8070
      - SECREY_KEY=HICjfJURXL74+/fB8AM/gIKsJLowIxMOiYJ/ruYT+qE=
      - REMOTE_SERVER_HOST=172.98.0.2
      - REMOTE_SERVER_PORT=8001
      - PROTOCOL=https
      - HEARTBEAT_INTERVAL_SECONDS=7
      - REQUEST_TIMEOUT=3

  c2-client-2:
    build:
      context: c2-client
    networks:
      - c2_network
    ports:
      - "8071:8071"
    environment:
      - CLIENT_PORT=8071
      - SECREY_KEY=HICjfJURXL74+/fB8AM/gIKsJLowIxMOiYJ/ruYT+qE=
      - REMOTE_SERVER_HOST=172.98.0.2
      - REMOTE_SERVER_PORT=8001
      - PROTOCOL=https
      - HEARTBEAT_INTERVAL_SECONDS=7
      - REQUEST_TIMEOUT=3
  
  # database:
  #   image: 'postgres:latest'
  #   networks:
  #     c2_network:
  #       ipv4_address: 172.98.0.3
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: postgress
  #     POSTGRES_PASSWORD: postgress
  #     POSTGRES_DB: postgress
  #   volumes: 
  #     - db:/var/lib/postgresql/data
  #     - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

networks:
  c2_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.98.0.0/16
# volumes:
#   db:
#     driver: local